### ISSUE TITLE
In Boot Menu 2.30 function keys (F1-F5) are processed as output characters

### ISSUE THREAD

**Issue by mr-GreyWolf** [RBSC/Carnivore2#27] opened 2020-03-25 16:31 UTC
For example:
F1 = COLOR
F2 = AUTO
F5 = RUN
and this leads to the execution of command equivalent to pressing the first character of the contents:
F1 = C - customize configuration
F2 = A - select entry for autostart 
F5 = R - reset MSX and start an entry

**Comment by Wierzbowsky** [comment] 2020-03-25 16:58
I would not call it a bug. It's unexpected behaviour of functional keys because the Boot Menu uses characters and not scancodes to identify buttons. This may be difficult to fix.

**Comment by Wierzbowsky** [comment] 2020-03-29 14:26
Fixed. Detecting gap between GETPNT and PUTPNT and if more than one character found, the keyboard buffer is killed and an unused character is inserted into the buffer to pass through the keypress handling routine (and do nothing for keypress).

Will be released in the next Boot Menu version.

**Comment by Wierzbowsky** [comment] 2020-07-03 11:09
Released in v2.40 on 03.07.2020

**Closed as completed by Wierzbowsky** 2020-07-03 11:09 UTC
Labels: Bug, Done, Released
