### ISSUE TITLE
Freezes when used with KONAMI SCC SOUND CARTRIDGE or FMPAC(Carnivore2 v2.50 Beta Testing Program)

### ISSUE THREAD

**Issue by uniskie** [RBSC/Carnivore2#70] opened 2022-03-21 06:48 UTC
This is a problem in the v2.50 Beta Testing Program.
 (bootMenu = Carnivore2_v250_BetaTesting_002)

Freezes when used with KONAMI SCC SOUND CARTRIDGE or FMPAC.

This issue occurred on all 1chipMSX, MX-10 and A1GT.

e.g.1
Slot1:Carnivore2
Slot2:KONAMI SOUND CARTRIDGE (SCC+)
... Freeze when Nextor starts.

e.g.2.
Slot1:KONAMI SOUND CARTRIDGE (SCC+)
Slot2:Carnivore2
... Freeze when Nextor starts.

e.g.3.
Slot1:Carnivore2
Slot2:FM-PAC
... Freeze when Nextor starts.

In all cases, holding down the "N" key while launching and disabling Nextor successfully launched the BASIC screen.

This problem did not occur when starting Carnivore2 alone.

**Comment by Wierzbowsky** [comment] 2022-03-21 10:39
Why closing the ticket? Is the problem real or it was something else affecting Carnivore's functionality?

**Comment by Wierzbowsky** [comment] 2022-03-21 10:57
@uniskie Could you please test with the previous Nextor version 2.1.0 Release or Beta and see if the problem still occurs? If it doesn't, then Nextor could be the problem, otherwise the firmware may be the reason.

Also, please test with Boot Menu 2.40 and both Nextor versions (new and old) to rule out that the Boot Menu is at fault. Thanks.

I have none of these machines, so I can't test myself...

**Comment by uniskie** [comment] 2022-03-24 06:29
I wasn't sure if I could write a topic about version 2.5.0β here, so I closed it once.

We don't have time for the test, so please wait a few days.

I don't know how to change the version of Nextor of Firmware, so I think it will be a test by changing only NEXTOR.SYS.

**Comment by uniskie** [comment] 2022-03-24 06:49
I will post the combinations that I already know.

 bootMenu2.5.0 +IDEDriver 2.5.0 + Firmware2.4.0 (Nextor 2.1.1 beta 1) ：This problem did not occur.

Other tests will take some time.

**Comment by Wierzbowsky** [comment] 2022-03-24 09:21
So, do I understand correctly, that with all the files from 2.50 (Boot Menu, Nextor, etc), but with firmware 2.40 the problem can't be reproduced?

**Comment by uniskie** [comment] 2022-03-25 04:20
That understanding is correct.

**Comment by uniskie** [comment] 2022-03-26 05:32
I did a new combination test.

bootMenu2.4.0 +IDEDriver 2.4.0 + Firmware2.5.0 (Nextor 2.1.1 beta 1) ＋ Nextor.SYS 210
...  Freeze when Nextor starts.

Probably there seems to be a problem with the firmware 2.5.0.

I don't know how to change the Nextor kernel, so that's all I can do.
If you need to test with Nextor Karnerl 2.1.0, please let me know how to change it.

**Comment by Wierzbowsky** [comment] 2022-04-12 08:12
Thanks for testing! I've checked with our hardware developer and he could not reproduce this problem on his system. So, we need additional information. Could you please make a video of the problem showing the booting process and the moment the machine freezes? It's important to see whether the disk is being accessed before freezing and whether the disk LED is on after the machine froze. Thanks.

**Comment by Wierzbowsky** [comment] 2022-04-13 15:15
Could you please try to reproduce this problem with the updated firmware? We made some changes to CF card handling to prevent bus direction conflict.

http://rbsc.su/files/Carnivore2_v250_CFfix.pof

**Comment by uniskie** [comment] 2022-04-16 01:01
I tested Carnivore2_v250_CFfix.pof and confirmed that the problem was resolved!
Thank you very much.

e.g.1
Slot1:Carnivore2
Slot2:KONAMI SOUND CARTRIDGE (SCC+)
... OK!

e.g.2.
Slot1:KONAMI SOUND CARTRIDGE (SCC+)
Slot2:Carnivore2
... OK!

e.g.3.
Slot1:Carnivore2
Slot2:FM-PAC
... OK!

**Comment by Wierzbowsky** [comment] 2022-04-16 02:45
Awesome, thanks!

**Closed as completed** 2022-04-30 23:13 UTC
Labels: Bug, Done, Priority
